const kinks = [
  '3+ Penetration',
  'Age Differences',
  'Age Progression',
  'Age Regression',
  'All the Way Through',
  'Anal Vore',
  'Anal',
  'Androgyny',
  'Animal Transformation',
  'Aphrodisiacs',
  'Ass to Mouth',
  'Ass Worship',
  'Auto-Fellatio',
  'Barbed Cocks',
  'Begging',
  'Belly Fucking',
  'Bimbofication',
  'Birthing',
  'Biting',
  'Blood',
  'Bloodplay',
  'Body Swapping',
  'Body Writing',
  'Bondage',
  'Branding',
  'Breeding',
  'Bukkake',
  'Caging',
  'Cervical Penetration',
  'Chastity',
  'Choking',
  'Chubby',
  'Clit Play',
  'CNC',
  'Cock Vore',
  'Condoms',
  'Corruption',
  'Creampie',
  'Crossdressing',
  'Crotch Sniffing',
  'Cum Bath',
  'Cum Enemas',
  'Cum',
  'Cuntboys',
  'Deepthroat',
  'Degradation',
  'Diapers',
  'Digestion',
  'Dirty Talking',
  'Docking',
  'Double Penetration',
  'Drug / Alcohol Use',
  'Ear Play',
  'Electric Toys',
  'Enemas',
  'Excessive Cum',
  'Exhibitionism',
  'Exotic Cocks',
  'Face Fucking',
  'Face Sitting',
  'Farting',
  'Felching',
  'Fellatio',
  'Femboys',
  'Femininity',
  'Feminization',
  'Feral',
  'Fisting',
  'Flexibility',
  'Food Play',
  'Foot Play',
  'Foreplay',
  'Foreskin Worship',
  'Frotting',
  'Gags',
  'Gangbangs',
  'Gender Transformation',
  'Glory Hole',
  'Group Sex',
  'Growth',
  'Hair Pulling',
  'Hand Cuffs',
  'Handjob / Fingering',
  'Hard Vore',
  'Horns',
  'Hotdogging',
  'Humiliation',
  'Hyper Asses',
  'Hyper Balls',
  'Hyper Breasts',
  'Hyper Cocks',
  'Hyper Fat',
  'Hyper Muscle',
  'Hyper Vaginas',
  'Hyper',
  'Hyper-Voluptuous',
  'Ice',
  'In Heat',
  'Incest',
  'Inflation',
  'Kissing',
  'Knotted Cocks',
  'Knotting',
  'Lactation',
  'Leash & Collar',
  'Licking',
  'Living Insertions',
  'Macrophilia',
  'Magic Users',
  'Male Pregnancy',
  'Masculinity',
  'Masturbation',
  'Messy',
  'Microphilia',
  'Mind Control',
  'Multiple Orgasms',
  'Musk',
  'Natural Musk',
  'Navel Play',
  'Nipple Penetration',
  'Nipple Piercings',
  'Nursing',
  'Objectification',
  'Objectophilia',
  'Oral Fixation',
  'Orgasm Control',
  'Oviposition',
  'Pain',
  'Paw Play',
  'Pegging',
  'Pet / Master',
  'Piercings',
  'Powerbottoming',
  'Pregnancy',
  'Prolapse',
  'Prostate Play',
  'Prostitution',
  'Public Humiliation',
  'Queefing',
  'Rimming',
  'Rubber / Elastic / Latex',
  'Saliva',
  'Scat',
  'Scissoring',
  'Scratching',
  'Sex Toys',
  'Sexual Frustration',
  'Shaving',
  'Sheath Play',
  'Shrinking',
  'Size Difference',
  'Slapping',
  'Slime',
  'Sloppy Seconds',
  'Small Breasts',
  'Smoking',
  'Snowballing',
  'Soft Vore',
  'Somnophilia',
  'Sounding',
  'Spanking',
  'Squirting',
  'Stomach Bulging',
  'Strap-ons',
  'Strip Tease',
  'Stuckage',
  'Swallowing',
  'Sweat',
  'Tail Pulling',
  'Tail Sex',
  'Tailsex',
  'Teasing',
  'Teeth Play',
  'Tentacles',
  'Throat Penetration',
  'Tickling',
  'Titfucking',
  'Tomboys',
  'Transformation',
  'Twinks',
  'Twins',
  'Udders',
  'Unusual Semen',
  'Urethra Play',
  'Vanilla Sex',
  'Virgin',
  'Vorarephilia',
  'Voyeurism',
  'Watersports',
  'Wax Play',
  'Whipping'
];


module.exports = {
  getAll: () => kinks,
  find: (value) => kinks.includes(value)
}
